axf/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
]

myApp/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from myApp import views
from mysite import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(\d+)/(\d+)/$', views.detail, name='detail'),  # 正则中分组的概念
    url(r'^grades/$', views.grades, name='grades'),
    url(r'^students/$', views.students, name='students'),
    url(r'^grades/(\d+)/$', views.grade_students, name='grade_students'),
    url(r'^addstudent/$', views.add_student, name='add_student'),
    url(r'^studentpage/(\d+)/$', views.student_page, name='student_page'),
    url(r'^attribute/$', views.attribute, name='attribute'),
    url(r'^get1/$', views.get1, name='get1'),
    url(r'^get2/$', views.get2, name='get2'),
    url(r'^showregister/$', views.show_register, name='show_register'),
    url(r'^register/$', views.register, name='register'),
    url(r'^showresponse/$', views.show_response, name='show_response'),
    url(r'^cookietest/$', views.cookie_test, name='cookie_test'),
    url(r'^redirect1/$', views.redirect1, name='redirect1'),
    url(r'^redirect2/$', views.redirect2, name='redirect2'),
    url(r'^index.html$', views.index1, name='index1'),
    url(r'^main/$', views.main, name='main'),
    url(r'^login/$', views.login, name='login'),
    url(r'^showmain/$', views.show_main, name='show_main'),
    url(r'^logout/$', views.my_logout, name='my_logout'),
    url(r'^good/(\d+)/$', views.good, name='good'),
    url(r'^better/$', views.better, name='better'),
    url(r'^home/$', views.home, name='home'),
    url(r'^csrf/$', views.csrf, name='csrf'),
    url(r'^showcsrf/$', views.show_csrf, name='show_csrf'),
    url(r'^verifycode/$', views.verify_code, name='verify_code'),
    url(r'^verifycodefile/$', views.verify_code_file, name='verify_code_file'),
    url(r'^verifycodecheck/$', views.verify_code_check, name='verify_code_check'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^savefile/$', views.save_file, name='save_file'),
    url(r'^ajaxstudents/$', views.ajax_students, name='ajax_student'),
    url(r'^studentsinfo/$', views.students_info, name='students_info'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^celery/$', views.celery, name='celery'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# 为了测试，另外配置的欢迎页面
from polls import views

urlpatterns = [
    url(r'^axf/', include('axf.urls', namespace='axf')),
    # 富文本编辑器
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),

    url(r'^myapp/', include('myApp.urls', namespace='myApp')),
    url(r'^bbs/', include('bbs.urls', namespace='bbs')),
    url(r'^movie/', include('movie.urls', namespace='movie')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^$', views.hello_django),
    url(r'^admin/', admin.site.urls),
]

myApp/models.py
# coding: utf-8
from django.db import models


# Create your models here.
from tinymce.models import HTMLField


class Grade(models.Model):
    grade_name = models.CharField(max_length=64, unique=True)
    grade_date = models.DateTimeField()
    grade_girl_num = models.IntegerField()
    grade_boy_num = models.IntegerField()
    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return self.grade_name

    class Meta:
        db_table = "grade"


class StudentManager(models.Manager):
    def get_queryset(self):
        return super(StudentManager, self).get_queryset().filter(is_delete=False)

    # 创建对象的方法二:
    # def create_student(self, name, age, gender, contend, grade, create_time, last_time, is_delete=False):
    #     student = self.model()
    #     student.student_name = name
    #     student.student_age = age
    #     student.student_gender = gender
    #     student.student_contend = contend
    #     student.student_grade = grade
    #     student.last_time = last_time
    #     student.create_time = create_time
    #     student.save()
    #     return student


class Student(models.Model):
    # 自定义模型管理器，如果只是创建管理类的实例，而不修改，和原始的objects没有qubie
    # student_objects = models.Manager()
    # 不能同时存在，否则不起作用。需要注意:原来views中objects需要替换为student_objects2
    # student_objects2 = StudentManager()

    # 为了省去后边该很多的麻烦，我觉得可以直接利用赋值去覆盖原有的objects
    objects = StudentManager()

    student_name = models.CharField(max_length=64)
    student_age = models.IntegerField(db_column='age')
    student_gender = models.BooleanField(default=True)
    student_contend = models.CharField(max_length=64)
    is_delete = models.BooleanField(default=False)

    # 关联外键
    student_grade = models.ForeignKey("Grade")

    create_time = models.DateTimeField(auto_now_add=True)
    last_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.student_name

    def get_name(self):
        """演示在模板中调用方法时，随便引入"""
        return self.student_name

    class Meta:
        """设置数据表的元信息，例如改变默认的数据表名，由appname_模型名，改为自定义"""
        db_table = "student"
        ordering = ['id',
                    # '-id',  # 倒序
                    ]

    # 方法一：在模型中，定义一个类方法创建对象；方法二在模型管理类中
    # 其实创建模型管理类实例对象后，覆盖了默认的objects，连下面的方法定义也可以省略了，就用原来的接口
    # 其实如果用了新名称，而没有覆盖，仍然可以用原来的方式创建对象。
    # @classmethod
    # def create_student(cls, name, age, gender, contend, grade, create_time, last_time, is_delete=False):
    #     student = cls(student_name=name, student_age=age,
    #                   student_gender=gender,student_contend=contend,
    #                   student_grade=grade, create_time=create_time,
    #                   last_time=last_time, is_delete=is_delete)
    #     return student

class Text(models.Model):
    # 富文本编辑器，效果似乎一般
    content = HTMLField()

myApp/views.py
# coding: utf-8
import os

from django.contrib.auth import logout
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse

# 从哪导入settings，有问题
from django.conf import settings
# from mysite import settings
from myApp.task import celery_demo
from myApp.models import Grade, Student


def index(request):
    # return HttpResponse('myApp is a good app')
    # 这里有问题，如果粗存在就会报错。
    student = Student.objects.get(pk=3)
    return render(request, 'myApp/index.html',
                  {'num': 666, 'stu': student, 'str': "myApp is a good app.",
                   'test': 777, 'code': "<h1>myApp is a escape app.</h1>"})


def index1(request):
    return HttpResponseRedirect('/myapp')


def detail(request, num, num2):
    return HttpResponse("detail-%s-%s" % (num, num2))


def grades(request):
    # 视图去模板里取数据
    grade_list = Grade.objects.all()
    # 将数据传递给模板，模板再渲染页面，将渲染好的页面返回浏览器
    return render(request, 'myApp/grades.html', {'grades': grade_list})


def students(request):
    student_list = Student.objects.all()
    # Show 25 students per page
    paginator = Paginator(student_list, 5)

    page = request.GET.get('page')
    try:
        students = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        students = paginator.page(1)
    except EmptyPage:
        # If page is out of range(e.g. 9999), deliver last page of results.
        students = paginator.page(paginator.num_pages)
    return render(request, 'myApp/students.html',
                  {'students': students, 'student_list': student_list})


def grade_students(request, grade_id):
    """点击班级，显示该班级的所有学生"""
    # 在多的一方直接过滤就能获得
    # student_list = Student.student_objects2.filter(student_grade_id=grade_id)

    # 加入模型管理类之后，就需要进行上面的替换这样的操作，
    # 可不可以直接覆盖objects？试一试，可以覆盖，这样就会省很多操作。
    student_list = Student.objects.filter(student_grade_id=grade_id)

    # # 获得对应的班级对象
    # grade = Grade.objects.get(pk=grade_id)
    #
    # # 获得班级下的所有学生对象列表
    # student_list = grade.student_set.all()

    # 仍然把上边的模板给它
    return render(request, 'myApp/students.html', {'students': student_list})


def add_student(request):
    grade = Grade.objects.get(pk=3)
    student = Student.objects.create(student_name="乔丹", student_age=50, student_gender=True,
                                     student_contend='篮球之神',
                                     student_grade=grade,
                                     create_time='2017-5-1', last_time='2017-10-17')
    # student = Student.objects.create_student("库里", 26, True, '库日天', grade, '2017-5-1', '2017-10-17')
    if student.student_gender:
        grade.grade_boy_num += 1
    else:
        grade.grade_girl_num += 1
    grade.save()
    # student.save()
    return HttpResponse("student ok")


def student_page(request, page):
    """分页显示学生"""
    # 有漏洞，没有处理不存在的情况
    page = int(page)
    student_list = Student.objects.all()[(page - 1) * 5: page * 5]
    return render(request, "myApp/students.html", {"students": student_list})


def attribute(request):
    return HttpResponse('attributes: --'
                        'path:%s --'
                        'method:%s --'
                        'encoding:%s --'
                        'GET:%s --'
                        'POST:%s --'
                        'FILES:%s --'
                        'COOKIES:%s --'
                        'session:%s' % (request.path, request.method,
                                        request.encoding, request.GET,
                                        request.POST, request.FILES,
                                        request.COOKIES, request.session))


def get1(request):
    """获取get传递的数据，两种方式"""
    a = request.GET.get('a')
    b = request.GET['b']
    c = request.GET.get('c')
    return HttpResponse(a + "    " + b + "    " + c)


def get2(request):
    """获取get传递的数据, 一个键对应多个值"""
    a = request.GET.getlist('a')
    a1 = a[0]
    a2 = a[1]
    c = request.GET['c']
    return HttpResponse(a1 + "    " + a2 + "    " + c)


def show_register(request):
    return render(request, 'myApp/register.html')


def register(request):
    name = request.POST.get('name')
    gender = request.POST.get('gender')
    age = request.POST.get('age')
    post = request.POST.getlist('hobby')
    return HttpResponse("<h1>register success</h1><br><hr>"
                        "<ol><li>%s</li><li>%s</li>"
                        "<li>%s</li><li>%s</li></ol>" % (name, gender, age, post))


def show_response(request):
    res = HttpResponse()
    print(res.content, res.charset, res.status_code)
    return res


def cookie_test(request):
    res = HttpResponse()
    cookie = request.COOKIES
    res.write("<h1>" + cookie["myApp"] + "</h1>")
    # cookie = res.set_cookie("myApp", 'better')
    return res


def redirect1(request):
    """重定向需要的是地址，是路径"""
    # return HttpResponseRedirect("/myapp/redirect2")
    # 可以使用html中url解析的格式, namespace和name不变，那么下面就不需要改动
    return redirect("myApp:redirect2")
    # 也可以传url路径
    # return redirect("/myapp/redirect2")


def redirect2(request):
    return HttpResponse("我是重定向地址，后的视图")


def main(request):
    # 取session
    username = request.session.get('username', default='游客')
    return render(request, 'myApp/main.html', {'username': username})


def login(request):
    return render(request, 'myApp/login.html')


def show_main(request):
    username = request.POST.get('username')

    # 存储session
    request.session['username'] = username

    # 设置过期时间，单位:秒
    # request.session.set_expiry(10)
    return redirect("/myapp/main")


def my_logout(request):
    # 退出时，清除session
    logout(request)
    # request.session.clear()
    # request.session.flush()
    return redirect("/myapp/main")


def good(request, page):
    """
    html中反向解析url传过来的参数必须接，
    合成的url要和urls正则中的匹配，
    有几个参数，就需要有几个圆括号。
    """
    return render(request, 'myApp/good.html', {'num': page})


def better(request):
    return render(request, 'myApp/better.html')


def home(request):
    return render(request, 'myApp/home.html')


def csrf(request):
    return render(request, 'myApp/csrf.html')


def show_csrf(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    return render(request, 'myApp/showcsrf.html',
                  {'username': username, 'password': password})


def verify_code(request):
    """生成验证码图片"""
    # 引入绘图模块
    from PIL import Image, ImageDraw, ImageFont

    # 引入随机模块函数
    import random

    # 自定变量， 用于画面的背景色、宽、高
    back_ground_color = (random.randrange(20, 100),
                         random.randrange(20, 100),
                         random.randrange(20, 100))
    width = 100
    height = 50

    # 创建画面对象
    im = Image.new('RGB', (width, height), back_ground_color)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    strings = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(4):
        rand_str += strings[random.randrange(0, len(strings))]
    # 构造字体对象
    font = ImageFont.truetype(r'C:\Windows\Fonts\Microsoft YaHei UI\MSYH.TTC', 40)
    # 构造字体颜色
    font_color1 = (255, random.randrange(0, 255), random.randrange(0, 255))
    font_color2 = (255, random.randrange(0, 255), random.randrange(0, 255))
    font_color3 = (255, random.randrange(0, 255), random.randrange(0, 255))
    font_color4 = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=font_color1)
    draw.text((25, 2), rand_str[1], font=font, fill=font_color2)
    draw.text((50, 2), rand_str[2], font=font, fill=font_color3)
    draw.text((75, 2), rand_str[3], font=font, fill=font_color4)
    # 释放画笔
    del draw
    # 存入session，用于做进一步验证
    request.session['verify'] = rand_str
    # 内存文件操作
    import io
    buf = io.BytesIO()
    # 将突破保持在内存中，文件类型为png
    im.save(buf, 'png')
    # 将内存中的图片数据返回给客户端， MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')


def verify_code_file(request):
    f = request.session.get("flag")
    strings = ''
    if f is False:
        strings = "请重新输入"
    request.session.clear()
    return render(request, 'myApp/verifycodefile.html', {'flag': strings})


def verify_code_check(request):
    code1 = request.POST.get("verify_code").upper()
    code2 = request.session["verify"].upper()
    if code1 == code2:
        return render(request, 'myApp/verifycuccess.html')
    else:
        request.session['flag'] = False
        return redirect("myApp:verify_code_file")


def upload(request):
    return render(request, 'myApp/upload.html')


def save_file(request):
    """上传文件必须是post请求"""
    if request.method == 'POST':
        file = request.FILES.get('file')
        # 合成文件在服务器端的路径
        file_path = os.path.join(os.path.join(settings.MEDIA_ROOT,
                                              'myApp/upload'), file.name)
        with open(file_path, 'wb') as fp:
            # 以文件流的形式一段一段接收
            for info in file.chunks():
                fp.write(info)
        return HttpResponse('上传成功')
    else:
        return HttpResponse("上传失败")


def ajax_students(request):
    return render(request, 'myApp/ajaxstudents.html')


def students_info(request):
    students = Student.objects.all()
    lists = []
    for student in students:
        lists.append([student.student_name, student.student_age])
    return JsonResponse({"data": lists})


def edit(request):
    return render(request, 'myApp/edit.html')


def celery(request):
    """分布式任务调度模块，解决耗时操作和执行定时任务"""
    # 添加到celery中执行，不会阻塞。但是还需要环境，需要启动redis和work

templates/myApp/ajaxstudents.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ajax请求</title>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
</head>
<body>
    <h1>学生信息列表</h1>
    <button id="btn">显示学生信息</button>
    <script type="text/javascript" src="{% static 'js/myApp.js'%}"></script>
</body>
</html>

templates/myApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        #header{
            width: 100%;height: 100px;background-color: red;
        }
        #footer{
            width: 100%;height: 100px;background-color: green;
        }
    </style>
    {% block title %}
        <title>基模板</title>
    {% endblock %}
</head>
<body>
    <div id="header">header</div>
    <div id="content-main">
        {% block content-main %}
            <div>继承后填充需要的内容</div>
        {% endblock %}
    </div>
    <div id="footer">footer</div>
</body>
</html>

templates/myApp/celery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>celery演示耗时操作</title>
</head>
<body>
    <h1>我是celery页面</h1>
</body>
</html>

templates/myApp/csrf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>csrf</title>
</head>
<body>
    <form action="{% url 'myApp:show_csrf' %}" method="post">
        {% csrf_token %}
        <label for="">姓名：<input type="text" name="username"></label>
        <hr>
        <label for="">密码：<input type="password" name="password"></label>
        <hr>
        <label for=""><input type="submit" value="登录"></label>
    </form>
</body>
</html>

templates/myApp/edit.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>富文本</title>
    <script type="text/javascript" src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
    <script type="text/javascript">
        tinyMCE.init({
            'mode': 'textareas',
            'theme': 'advanced',
            'width': 800,
            'height': 600
        })
    </script>
</head>
<body>
<form action="#" method="post">
    {% csrf_token %}
    <label for="">
        content:
        <textarea name="str" id="" cols="30" rows="10">
        myapp is the best app.提交功能未完成。写博客时有用，存到数据库。
        </textarea>
    </label>
    <label for=""><input type="submit" value="提交"></label>
</form>
</body>
</html>

templates/myApp/good.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Good</title>
</head>
<body>
    <h1>good--{{ num }}</h1>
</body>
</html>

templates/myApp/grades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>班级信息</title>
</head>
<body>
    <h1>班级信息列表</h1>
    <ul>
        {% for grade in  grades%}
        <li>
            <a href="{{ grade.id }}">{{ grade.grade_name }}</a>
        </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/myApp/index.html
<!DOCTYPE html>
{% load static %}
{#{% load static from staticfiles %} 四班的老师这样配，不知什么原因#}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/myApp.js' %}"></script>
</head>
<body>
    <h1>myApp is ok</h1>
    <h1>调用对象的属性：{{ stu.student_name }}--{{ stu.student_contend }}--*{{ num }}*</h1>
    <h1>调用对象的方法（但是不能传递参数）：{{ stu.get_name }}--{{ stu.student_contend }}--*{{ num }}*</h1>
    <h1>测试过滤器：{{ str|upper }}</h1>
    {% autoescape off %}
        {{ code }}<h1 style="color:red ">处理多个转义，会把引号内的内容当做文本；当为off时，显示原始内容</h1>
    {% endautoescape %}
{#    {{ code|escape }}#}
    {{ code|safe }}<h1 style="color:green">处理单个不需要转义的字符串，不需要转义就是以html格式显示</h1>
    <h1>{{ str }}</h1>
    <h1>{{ test|default:'没有或False,解决变量不存在时显示默认值的问题，default后冒号后不能有空格' }}</h1>
    <h1>利用模板语言计算：加减乘除 num = {{ num }}</h1>
    <h1>num + 10 = {{ num|add:10 }}</h1>
    <h1>num - 10 = {{ num|add:-10 }}</h1>
    <h1>num * 10 = {% widthratio num 1 10 %}</h1>
    <h1>num / 10 = {% widthratio num 10 1 %}</h1>
    <img src="{% static 'img/example2.jpg' %}" alt="example.jpg">
</body>
</html>

templates/myApp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    <form action="{% url 'myApp:show_main' %}" method="post">
        {% csrf_token %}
        <label for="">用户名:<input type="text" name="username"></label>
        <input type="submit" value="登录">
    </form>
</body>
</html>

templates/myApp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的</title>
</head>
<body>
    <h1>欢迎：{{ username|default:'游客' }}</h1>
    <a href="{% url 'myApp:login' %}">登录</a>
    <a href="{% url 'myApp:my_logout' %}">退出登录</a>
</body>
</html>

templates/myApp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    <form action="{% url 'myApp:register' %}" method="post">
        {% csrf_token %}
        <label for="">姓名：<input type="text" name="name"></label>
        <label for="">性别：<input type="radio" name="gender" value="1">男
            <input type="radio" name="gender" value="0">女
        </label>
        <label for="">年龄：<input type="text" name="age"></label>
        <label for="">爱好：
            <label for=""><input type="checkbox" name="hobby" value="power">权利：</label>
            <label for=""><input type="checkbox" name="hobby" value="money">金钱：</label>
            <label for=""><input type="checkbox" name="hobby" value="boy">美女：</label>
            <label for=""><input type="checkbox" name="hobby" value="girl">俊男：</label>
        </label>
        <input type="submit" value="注册">
    </form>
</body>
</html>

templates/myApp/showcsrf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>showcsrf</title>
</head>
<body>
    <h1>name: {{ username }}</h1>
    <h1>pass: {{ password }}</h1>
</body>
</html>

templates/myApp/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传文件</title>
</head>
<body>
    <form action="{% url 'myApp:save_file' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for=""><input type="file" name="file"></label>
        <label for=""><input type="submit" value="上传"></label>
    </form>
</body>
</html>

templates/myApp/verifycuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录成功</title>
</head>
<body>
    <h1>恭喜，登录成功</h1>
</body>
</html>