axf/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# 为了测试，另外配置的欢迎页面
from polls import views

urlpatterns = [
    url(r'^axf/', include('axf.urls', namespace='axf')),
    # 富文本编辑器
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),

    url(r'^myapp/', include('myApp.urls', namespace='myApp')),
    url(r'^bbs/', include('bbs.urls', namespace='bbs')),
    url(r'^movie/', include('movie.urls', namespace='movie')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^$', views.hello_django),
    url(r'^admin/', admin.site.urls),
]

axf/models.py
from django.db import models


# Create your models here.
class Wheel(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)
    # id_delete = models.BooleanField(default=False, null=True)  加入这句需要改数据很麻烦


class Nav(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)


class Mustbuy(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)


class Shop(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)


class MainShow(models.Model):
    trackid = models.CharField(max_length=10)
    name = models.CharField(max_length=20)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=10)
    brandname = models.CharField(max_length=20)

    img1 = models.CharField(max_length=100)
    childcid1 = models.CharField(max_length=10)
    productid1 = models.CharField(max_length=10)
    longname1 = models.CharField(max_length=50)
    price1 = models.CharField(max_length=10)
    marketprice1 = models.CharField(max_length=10)

    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=10)
    productid2 = models.CharField(max_length=10)
    longname2 = models.CharField(max_length=50)
    price2 = models.CharField(max_length=10)
    marketprice2 = models.CharField(max_length=10)

    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=10)
    productid3 = models.CharField(max_length=10)
    longname3 = models.CharField(max_length=50)
    price3 = models.CharField(max_length=10)
    marketprice3 = models.CharField(max_length=10)


# 分类模型
class FoodTypes(models.Model):
    typeid = models.CharField(max_length=10)
    typename = models.CharField(max_length=20)
    typesort = models.IntegerField()
    childtypenames = models.CharField(max_length=150)


# 商品模型类
class Goods(models.Model):
    # 商品id
    productid = models.CharField(max_length=10)
    # 商品图片
    productimg = models.CharField(max_length=150)
    # 商品名称
    productname = models.CharField(max_length=50)
    # 商品长名称
    productlongname = models.CharField(max_length=100)
    # 是否精选
    isxf = models.NullBooleanField(default=False)
    # 是否买一赠一
    pmdesc = models.CharField(max_length=10)
    # 规格
    specifics = models.CharField(max_length=20)
    # 价格
    price = models.CharField(max_length=10)
    # 超市价格
    marketprice = models.CharField(max_length=10)
    # 组id
    categoryid = models.CharField(max_length=10)
    # 子类组id
    childcid = models.CharField(max_length=10)
    # 子类组名称
    childcidname = models.CharField(max_length=10)
    # 详情页id
    dealerid = models.CharField(max_length=10)
    # 库存
    storenums = models.IntegerField()
    # 销量
    productnum = models.IntegerField()


# 用户模型类
class User(models.Model):
    # 用户账号，要唯一
    userAccount = models.CharField(max_length=20, unique=True)
    # 密码
    userPasswd = models.CharField(max_length=20)
    # 昵称
    userName = models.CharField(max_length=20)
    # 手机号
    userPhone = models.CharField(max_length=20)
    # 地址
    userAdderss = models.CharField(max_length=100)
    # 头像路径
    userImg = models.CharField(max_length=150)
    # 等级
    userRank = models.IntegerField()
    # touken验证值，每次登陆之后都会更新
    userToken = models.CharField(max_length=50)

    @classmethod
    def createuser(cls, account, passwd, name, phone, address, img, rank, token):
        u = cls(userAccount=account, userPasswd=passwd, userName=name, userPhone=phone, userAdderss=address,
                userImg=img, userRank=rank, userToken=token)
        return u

axf/views.py
from django.shortcuts import render

# Create your views here.
from .models import Wheel, Nav, Mustbuy, Shop, MainShow, FoodTypes, Goods


def home(request):
    wheels_list = Wheel.objects.all()
    nav_list = Nav.objects.all()
    must_buy_list = Mustbuy.objects.all()
    shop_list = Shop.objects.all()
    shop1 = shop_list[0]
    shop2 = shop_list[1:3]
    shop3 = shop_list[3:7]
    shop4 = shop_list[7:11]
    main_list = MainShow.objects.all()
    return render(request, 'axf/home.html',
                  {"wheels_list": wheels_list,
                   'nav_list': nav_list,
                   'must_buy_list': must_buy_list,
                   "shop1": shop1, "shop2": shop2,
                   "shop3": shop3, "shop4": shop4,
                   'main_list': main_list})


def market(request, categoryid, cid, sortid):
    leftSlider = FoodTypes.objects.all()

    if cid == '0':
        productList = Goods.objects.filter(categoryid=categoryid)
    else:
        productList = Goods.objects.filter(categoryid=categoryid, childcid=cid)

    # 排序
    if sortid == '1':
        productList = productList.order_by("productnum")
    elif sortid == '2':
        productList = productList.order_by("price")
    elif sortid == '3':
        productList = productList.order_by("-price")

    group = leftSlider.get(typeid=categoryid)
    childList = []
    # 全部分类:0#进口水果:103534#国产水果:103533
    childnames = group.childtypenames
    arr1 = childnames.split("#")
    for str in arr1:
        # 全部分类:0
        arr2 = str.split(":")
        obj = {"childName": arr2[0], "childId": arr2[1]}
        childList.append(obj)

    return render(request, 'axf/market.html',
                  {"leftSlider": leftSlider, "productList": productList, "childList": childList,
                   "categoryid": categoryid, "cid": cid})


def cart(request):
    return render(request, 'axf/cart.html')


def mine(request):
    return render(request, 'axf/mine.html')


from django.contrib.staticfiles.finders import FileSystemFinder, AppDirectoriesFinder

def login(request):
    pass
def register(request):
    pass

templates/axf/base.html
<!DOCTYPE html>

{% load static from staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}
        <title>base</title>
    {% endblock %}
    <meta name="viewport" content="width=device-width,initial-scale=1.0,
    maximum-scale=1.0,user-scalable=0">
    <link rel="stylesheet" type="text/css" 
          href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" 
          href="{% static 'main/css/swiper.min.css' %}">
    <link rel="stylesheet" type="text/css" 
          href="{% static 'main/css/reset.css' %}">
    <link rel="stylesheet" type="text/css" 
          href="{% static 'main/css/base.css' %}">
    
    <script type="text/javascript" charset="utf-8"
            src="{% static 'main/js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8"
            src="{% static 'main/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8"
            src="{% static 'main/js/swiper.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8"
            src="{% static 'main/js/base.js' %}"></script>
    
    {% block linkscript %}
    
    {% endblock %}
</head>
<body>
    <header></header>
    <div>
        {% block base %}

        {% endblock %}
    </div>
    <footer>
        <a class="home" href="{% url 'axf:home' %}">
            <dl>
                <dt><span><img src="{% static 'main/img/home.png' %}" width="20px" alt=""></span></dt>
                <dd>主页</dd>
            </dl>
        </a>
        <a class="market" href="{% url 'axf:market' 104749 0 0 %}">
            <dl>
                <dt><span><img src="{% static 'main/img/market.png' %}" width="20px" alt=""></span></dt>
                <dd>闪送超市</dd>
            </dl>
        </a>
        <a class="cart" href="{% url 'axf:cart' %}">
            <dl>
                <dt><span><img src="{% static 'main/img/cart.png' %}" width="20px" alt=""></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a class="mine" href="{% url 'axf:mine' %}">
            <dl>
                <dt><span><img src="{% static 'main/img/mine.png' %}" width="20px" alt=""></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
</body>
</html>

templates/axf/cart.html
{% extends 'axf/base.html' %}

{% load static from staticfiles %}

{% block linkscript %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'cart/css/cart.css' %}">
    <script type="text/javascript" charset="utf-8"
            src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

{% block title %}
    <title>cart</title>
{% endblock %}

{% block base %}
    <h1>axf is a good app</h1>
    <h1>axf is a nice app</h1>
    <h1>axf is a cool app</h1>
    <h1>axf is a handsome app</h1>
    <h1>cart</h1>
{% endblock %}

templates/axf/home.html
{% extends 'axf/base.html' %}

{% load static from staticfiles %}

{% block linkscript %}
    <link rel="stylesheet" type="text/css"
      href="{% static 'home/css/home.css' %}">
    <script type="text/javascript" charset="utf-8"
        src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

{% block title %}
    <title>home</title>
{% endblock %}

{% block base %}
{#    <h1>axf is a good app</h1>#}
{#    <h1>axf is a nice app</h1>#}
{#    <h1>axf is a cool app</h1>#}
{#    <h1>axf is a handsome app</h1>#}
{#    <h1>home</h1>#}
    <div id="home">
        <!--轮播-->
        <section class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                {% for item in wheels_list %}
                    <div class="swiper-slide">
                        <a href="#"><img src="{{ item.img }}" alt=""></a>
                    </div>
                {% endfor %}
            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </section>

        <section class="topMenu">
            <nav>
                <ul>
                    {% for item in nav_list %}
                        <li>
                            <a href="#">
                                <img src="{{ item.img }}" alt="">
                                <span>{{ item.name }}</span>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
            <menu class="swiper-container swiperMenu" id="swiperMenu">
                <ul class="swiper-wrapper">
                    {% for item in must_buy_list %}
                        <li class="swiper-slide">
                            <a href="#"><img src="{{ item.img }}" alt=""></a>
                        </li>
                    {% endfor %}
                </ul>
            </menu>
        </section>

        <section class="CVS">
            <h2>
                <img src="{{shop1.img}}" alt="{{shop1.name}}"/>
            </h2>

            <fieldset>
                {% for x in shop2 %}
                    <a href="#">
                        <img src="{{x.img}}" alt="{{x.name}}"/>
                    </a>
                {% endfor %}
            </fieldset>

            <ul>
                {% for x in shop3 %}
                    <li>
                        <a href="#">
                            <img src="{{x.img}}" />
                            <span>{{x.name}}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>

            <ol>
                {% for x in shop4 %}
                    <li><a href="#"><img src="{{x.img}}" alt="{{x.name}}"/></a></li>
                {% endfor %}
            </ol>
        </section>

        <section class="mainInfo">
            {% for item in main_list%}
                <section>
                    <h3>
                        {{item.name}}
                        <a href="#">更多></a>
                        <span></span>
                    </h3>
                    <div>
                        <a href="#"><img src="{{item.img}}" alt="item.name"/></a>
                    </div>
                    <ul>
                        <li>
                            <a href="#">
                                <img src="{{item.img1}}"/>
                                <span class="description">{{item.longname1}}</span>
                                <span>¥{{item.price1}}</span>
                                <s>¥{{item.marketprice1}}</s>
                            </a>
                            <button><span>&#43;</span></button>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{{item.img2}}"/>
                                <span class="description">{{item.longname2}}</span>
                                <span>¥{{item.price2}}</span>
                                <s>¥{{item.marketprice2}}</s>
                            </a>
                            <button><span>&#43;</span></button>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{{item.img3}}"/>
                                <span class="description">{{item.longname3}}</span>
                                <span>¥{{item.price3}}</span>
                                <s>¥{{item.marketprice3}}</s>
                            </a>
                            <button><span>&#43;</span></button>
                        </li>
                    </ul>
                </section>
            {% endfor %}
        </section>
    </div>
{% endblock %}

templates/axf/market.html
{% extends 'axf/base.html' %}

{% load static from staticfiles %}

{% block linkscript %}
    <link rel="stylesheet" type="text/css"
      href="{% static 'market/css/market.css' %}">
    <script type="text/javascript" charset="utf-8"
        src="{% static 'market/js/market.js' %}"></script>
{% endblock %}

{% block title %}
    <title>market</title>
{% endblock %}

{% block base %}
{#    <h1>axf is a good app</h1>#}
{#    <h1>axf is a nice app</h1>#}
{#    <h1>axf is a cool app</h1>#}
{#    <h1>axf is a handsome app</h1>#}
{#    <h1>market</h1>#}
    <div id="market">
        <aside>
            <menu>
                <ul>
                    {% for item in leftSlider %}
                    <li>
                        <span class="yellowSlide"></span>
                        <a href="{% url 'axf:market' item.typeid 0 0 %}">{{item.typename}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </menu>
        </aside>

        <section>
            <nav>
                <ul>
                    <li>
                        <span id="alltypebtn">全部类型
                            <span class="glyphicon glyphicon-chevron-down" style="font-weight: 100"></span>
                        </span>
                    </li>
                    <li>
                        <span id="showsortbtn">综合排序
                            <span class="glyphicon glyphicon-chevron-down" style="font-weight: 100"></span>
                        </span>
                    </li>
                </ul>
            </nav>

            <menu>
                <ul>
                    {% for item in productList %}
                    <li>
                        <a href="#">
                            <img src="{{item.productimg}}" />
                            <article class="shoppingInfo">
                                <h6>{{item.productlongname}}</h6>
                                <p class="detailTag"><span>精选</span><span>{{item.pedesc}}</span></p>
                                <span class="unit">{{item.specifics}}</span>
                                <p class="price"><span>￥{{item.price}}</span><s><span>￥{{item.marketprice}}</span></s></p>
                            </article>
                        </a>
                        <section>
                            <button ga="{{item.productid}}" class="subShopping">-</button>
                            <span id="{{item.productid}}">0</span>
                            <button ga="{{item.productid}}" class="addShopping">+</button>
                        </section>
                    </li>
                    {% endfor %}
                </ul>

                <div id="typediv">
                    <div>
                        {% for item in childList %}
                        <a href="{% url 'axf:market' categoryid item.childId 0 %}"><span>{{item.childName}}</span></a>
                        {% endfor %}
                    </div>
                </div>

                <div id="sortdiv">
                    <div>
                        <a href="{% url 'axf:market' categoryid cid 0 %}" class="sorta"><span>综合排序</span></a>
                        <a href="{% url 'axf:market' categoryid cid 1 %}" class="sorta"><span>销量排序</span></a>
                        <a href="{% url 'axf:market' categoryid cid 2 %}" class="sorta"><span>价格最低</span></a>
                        <a href="{% url 'axf:market' categoryid cid 3 %}" class="sorta"><span>价格最高</span></a>
                    </div>
                </div>
            </menu>
        </section>
    </div>
{% endblock %}

templates/axf/mine.html
{% extends 'axf/base.html' %}

{% load static from staticfiles %}

{% block linkscript %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'mine/css/mine.css' %}">
    <script type="text/javascript" charset="utf-8"
            src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

{% block title %}
    <title>mine</title>
{% endblock %}

{% block base %}
{#    <h1>axf is a good app</h1>#}
{#    <h1>axf is a nice app</h1>#}
{#    <h1>axf is a cool app</h1>#}
{#    <h1>axf is a handsome app</h1>#}
{#    <h1>mine</h1>#}
<div id="mine">
    <section class="fixed">
		<span class="glyphicon glyphicon-user"></span>
		<p><a href="{% url 'axf:login' %}">未登录</a></p>
		<p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
		<a id="regis" href="{% url 'axf:register' %}">注册</a>
		<p><span class="glyphicon glyphicon-heart"></span>商品收藏</p>
	</section>

    <section class="mine">
		<p>
			<span>我的订单</span><a>查看全部订单&gt;</a>
		</p>
		<nav id="nav">
			<ul>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-usd"></span></dt>
							<dd>代付款</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-envelope"></span></dt>
							<dd>待收货</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-pencil"></span></dt>
							<dd>待评价</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-retweet"></span></dt>
							<dd>退款/售后</dd>
						</dl>
					</a>
				</li>
			</ul>
		</nav>


		<menu>
			<ul>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
							<dd>积分商城</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-credit-card"></span></dt>
							<dd>优惠券</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-import"></span></dt>
							<dd>收货地址</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
							<dd>客服/反馈</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-asterisk"></span></dt>
							<dd>关于我们</dd>
						</dl>
					</a>
				</li>
			</ul>
		</menu>
		<p><a href="#">退出当前账号</a></p>
	</section>
</div>
{% endblock %}