axf/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
]

movie/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

# 下面这种是在生产环境中配置静态文件和上传文件的方法，后面加上stctic等等，
# 但前提：需要在settings.py中配置STATIC_URL、STATIC_ROOT、MEDIA_URL、MEDIA_ROOT，
# 为了媒体文件不影响静态文件，所以static和media分开配置
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^detail/(?P<movie_id>\d+)/$', views.detail, name='detail'),
    url(r'^detail3', views.detail3, name='detail3'),
    url(r'^err/$', views.err, name='err'),
    url(r'^upload/$', views.upload, name='upload'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# 为了测试，另外配置的欢迎页面
from polls import views

urlpatterns = [
    url(r'^axf/', include('axf.urls', namespace='axf')),
    # 富文本编辑器
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),

    url(r'^myapp/', include('myApp.urls', namespace='myApp')),
    url(r'^bbs/', include('bbs.urls', namespace='bbs')),
    url(r'^movie/', include('movie.urls', namespace='movie')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^$', views.hello_django),
    url(r'^admin/', admin.site.urls),
]

movie/models.py
# coding:utf8
from django.db import models

'''
电影模型
名字
上映时间，
片长，
又名，

    导演 多对多
    编剧 多对多
    演员 多对多
    类型 多对多
    国家/地区 多对一
    语言 多对一
'''


# 电影模型的管理类，这样在不删除数据库里禁播的数据的情况下，
# 实现了在站点后台看不到禁播数据的目的
class MovieManager(models.Manager):
    def get_queryset(self):
        return super(MovieManager, self).get_queryset().filter(is_ban=False)


# 人类信息的父类
class Person(models.Model):
    pname = models.CharField(max_length=128, verbose_name='姓名')
    pxingbie = models.BooleanField(default=True, verbose_name='性别')
    pchusheng = models.DateTimeField(auto_now_add=True, verbose_name='出生日期')
    pchushengdi = models.CharField(max_length=64, verbose_name='出生地')
    pjianjie = models.TextField(verbose_name='简介')
    purl = models.CharField('肖像', max_length=512)

    def __str__(self):
        return self.pname

    class Meta:
        # 代表这个模型是一个虚拟模型，在迁移时不会被编译
        abstract = True


class Guojia(models.Model):
    gjname = models.CharField(max_length=32)

    def __str__(self):
        return '国家: %s.' % self.gjname


class Diqu(models.Model):
    dqname = models.CharField(max_length=32)

    def __str__(self):
        return '地区: %s.' % self.dqname


class Yuyan(models.Model):
    lname = models.CharField(max_length=32)

    def __str__(self):
        return '语言: %s.' % self.lname


class Movie(models.Model):
    # movie_objects = MovieManager()
    # 下面这种操作是原来操作的优化版本，这样似乎就不会改变原来的接口
    objects = MovieManager()

    mname = models.CharField(max_length=128)
    shangying = models.DateField(auto_now_add=True)
    pianchang = models.IntegerField(default=90)
    youming = models.CharField(max_length=128)
    jianjie = models.TextField()
    url = models.CharField(verbose_name='封面', max_length=512)
    is_ban = models.BooleanField(default=False)

    # 通过Django Console创建的时候需要传入对象，例如国家对象，而不是名字
    guojia = models.ForeignKey(Guojia)
    diqu = models.ForeignKey(Diqu)
    yuyan = models.ForeignKey(Yuyan)

    def __str__(self):
        return '电影: %s' % self.mname

    class Meta:
        # db_table
        ordering = ['shangying']


class Daoyan(Person):
    movie = models.ManyToManyField(Movie)

    def __str__(self):
        return '导演: %s.' % self.pname


class Bianju(Person):
    movie = models.ManyToManyField(Movie)

    def __str__(self):
        return '编剧: %s.' % self.pname


class Yanyuan(Person):
    movie = models.ManyToManyField(Movie)

    def __str__(self):
        return '演员: %s.' % self.pname


class Leixing(models.Model):
    lxname = models.CharField(max_length=32)

    movie = models.ManyToManyField(Movie)

    def __str__(self):
        return '类型: %s.' % self.lxname

movie/views.py
import os

from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Movie


# Create your views here.
def index(request):
    movie_list = Movie.objects.all().filter(is_ban=False)

    return render(request, 'movie/index.html', {'movie_list': movie_list})


def detail(request, movie_id):
    try:
        movie = get_object_or_404(Movie, pk=movie_id)
    except:
        return render(request, 'movie/err.html', {'err_message': '查询错误'})
    else:
        return render(request, 'movie/detail.html', {'movie': movie})


def detail3(request):
    # movie_id = request.GET['movie_id']
    # get方法比较安全，但还不是最好，最佳方案是使用get_objects_or_404快捷方式
    movie_id = request.GET.get('movie_id', default=None)
    try:
        if movie_id is not None:
            movie = Movie.objects.get(pk=movie_id)
    except:
        # return HttpResponse('<h3>错误的电影id</h3>')，这是演示反向解析
        return HttpResponseRedirect(reverse('movie:err'))
    else:
        return render(request, 'movie/detail.html', {'movie': movie})


def err(request, movie_id):
    # 使用快捷键模块，是为了保持松散耦合
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movie/err.html', {'movie': movie})


def upload(request):
    if request.method == 'POST':
        file = request.FILES['file']
        file_path = os.path.join(settings.MEDIA_ROOT, file.name)
        with open(file_path, 'wb') as fp:
            for info in file.chunks():
                fp.write(info)
    return HttpResponse('上传文件成功')

templates/movie/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>电影信息</title>
</head>
<body>
    <h5>电影名: {{ movie.mname }}</h5>
    <div><img src="{{ movie.url }}" alt="" width="100px"></div>
    <ul>
        {% for yanyuan in movie.yanyuan_set.all %}
            <li>
                {{ yanyuan.pname }}
            </li>
        {% empty %}
            此电影无演员
        {% endfor %}
    </ul>
</body>
</html>

templates/movie/err.html
{% extends 'admin/404.html' %}
{% load i18n %}

{% load static %}

{% block content %}
    <h2>{% trans 'Page not found' %}</h2>
    <p>{% trans "We're sorry, but the requested page could not be found." %}</p>
    <h3 style="color:red">{{ err_message }}</h3>
    <div><img src="{% static 'img/example.jpg' %}"
              alt="alt属性是当图片文件不存在时，显示的文字，例如一些纯文本浏览器"
              width="200px">
    </div>
    <div>
        <form action="{% url 'movie:upload' %}" method="Post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>请上传文件</p>
            <p>暂时没有显示文件的页面，有时间，再加上</p>
            <input type="file" name="file">
            <input type="submit" value="上传">
        </form>
    </div>
{% endblock %}

templates/movie/index.html
{% extends 'admin/base.html' %}
{% load i18n static %}

{% block title %}电影列表{% endblock %}

{% block content %}
    <ul>
        {% for movie in movie_list %}
            <li>
                <div>电影名称: {{ movie.mname }}</div>
                <div><a href="{% url 'movie:detail' movie.id %}"><img src="{{ movie.url }}" width='100px' alt=""></a></div>
{#                <div><a href="/movie/detail3?movie_id={{ movie.id }}/"><img src="{{ movie.url }}" width='100px' alt=""></a></div>#}
            </li>
        {% empty %}
            没有电影
        {% endfor %}
    </ul>
{% endblock %}

templates/movie/upload.html
{% extends 'admin/base.html' %}

{% load static %}

{% block title %}文件上传{% endblock %}

{% block content %}
    待补充
{% endblock %}